server:
  port: 8080
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 5 # Envoie un signal toutes les 5s (au lieu de 30s)
    lease-expiration-duration-in-seconds: 10 # Si pas de signal après 10s, considère l'instance morte
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true 
      routes:
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/categories/**    
        - id: product-service
          uri: lb://product-service 
          predicates:
            - Path=/products/**

# Configuration d'Actuator pour exposer les points de contrôle
management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,gateway,health,refresh"
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - [${spring.application.name}] - %msg%n"


