server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #prefer-ip-address: true
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true 
      routes:
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/categories/**    
        - id: product-service
          uri: lb://product-service 
          predicates:
            - Path=/products/**
management:
  endpoints:
    web:
      exposure:
        include: "gateway,health,info"

logging:
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - [${spring.application.name}] - %msg%n"


