server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webstoredb?createDatabaseIfNotExist=true
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  show-sql: true

# Configuration du client Eureka pour l'enregistrement
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5 # Envoie un signal toutes les 5s (au lieu de 30s)
    lease-expiration-duration-in-seconds: 10 # Si pas de signal après 10s, considère l'instance morte
    

# Exposition des points de contrôle pour Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,refresh"
logging:
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - [${spring.application.name}] - %msg%n"