server:
  port: ${PORT}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost


## Configuration Gmail Service
spring:
 mail:
  host: ${SPRING_MAIL_HOST}
  port: ${SPRING_MAIL_PORT}
  username: ${SPRING_MAIL_USERNAME}
  password: ${SPRING_MAIL_PASSWORD}
  properties:
    mail:
      smtp: 
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000

# Pour voir ce qui se passe dans le registre
management:
  endpoints:
    web:
      exposure:
        include: "*"