server:
  port: 8082

spring:
  # Configuration de la base de données H2 (Propre à ce microservice)
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Configuration JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # Configuration Thymeleaf pour le rendu des vues
  thymeleaf:
    cache: false # Désactivé pour le développement (rafraîchissement direct)
    prefix: classpath:/templates/
    suffix: .html

# Configuration du client Eureka pour l'enregistrement
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    # Utilise l'IP plutôt que le nom d'hôte pour éviter les soucis de DNS en local
    #prefer-ip-address: true
    #instance-id: ${spring.application.name}:${random.value}
    hostname: localhost

# Exposition des points de contrôle pour Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,refresh"