server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  # Configuration de la base de données H2 (Propre à ce microservice)
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Configuration JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # Configuration Thymeleaf pour le rendu des vues
  thymeleaf:
    cache: false # Désactivé pour le développement (rafraîchissement direct)
    prefix: classpath:/templates/
    suffix: .html

# Configuration du client Eureka pour l'enregistrement
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Exposition des points de contrôle pour Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,refresh"